version: "3"
services:
  planner:
    build: ./planner
    ports:
    - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway

  worker:
      build: ./worker
      ports:
      - 3000:3000
      extra_hosts:
        - host.docker.internal:host-gateway